apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-deploy
  namespace: lab-hpa
  labels:
    app: my-hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-hpa
  template:
    metadata:
      labels:
        app: my-hpa
    spec:
      containers:
        - name: hpa-container
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"