apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azuredisk-csi-lab
  resources:
    requests:
      storage: 15Gi