apiVersion: v1
kind: Pod
metadata:
  name: pod-dev-rbac
  namespace: dev
  labels:
    app: pod-dev-rbac
spec:
  containers:
    - name: aspnetapp-image
      image: mcr.microsoft.com/dotnet/samples:aspnetapp
      ports:
        - containerPort: 80
          protocol: TCP