apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    run: webapp
spec:
  containers:
    - name: webapp
      image: 040519/cna-webapp
      env:
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:
              name: webapp-cm
              key: APP_COLOR
