name: API Security Scan

on:
  push:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Start Juice Shop
      run: |
        docker run -d -p 3000:3000 bkimminich/juice-shop
        sleep 40

    - name: Run ZAP Full Scan
      run: |
        docker run --rm \
        -v $(pwd):/zap/wrk \
        zaproxy/zap-stable \
        zap-full-scan.py \
        -t http://host.docker.internal:3000 \
        -a \
        -j \
        -m 25 \
        -z "-config scanner.attackStrength=HIGH -config scanner.alertThreshold=LOW" \
        -r zap-report.html

    - name: Upload ZAP report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: zap-report.html
